### ISSUE TITLE
Request body may not be read

### ISSUE THREAD

**Issue by tomasbedrich** [PoorHttp/PoorWSGI#35]
Based on [this line](https://github.com/PoorHttp/PoorWSGI/blob/c245ccc878ade130e78802cbc1dc07da40c9ff55/poorwsgi/request.py#L719), is it possible for request body to be left unread? This may potentially break uwsgi:

> If an HTTP request has a body (like a POST request generated by a form), you have to read (consume) it in your application. If you do not do this, the communication socket with your webserver may be clobbered. If you are lazy you can use the post-buffering option that will automatically read data for you. For Rack applications this is automatically enabled.

(https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html)

**Comment by ondratu** [comment]
Hmm, that should be problem but:

- uwsgi do post-buffering in depend on  `Content-Length` header just like PoorWSGI, and i guess, that is same in other software
- If i understand https://www.rfc-editor.org/rfc/rfc9112#section-6.3 right, it is denied by RFC send request with body without `Content-Length` or `Transfer-Encoding`, so i expect, that all standard clients (included HTTP proxies) don't do that.

> A user agent that sends a request that contains a message body MUST send either a valid [Content-Length](https://www.rfc-editor.org/rfc/rfc9112#body.content-length) header field or use the chunked transfer coding. A client MUST NOT use the chunked transfer coding unless it knows the server will handle HTTP/1.1 (or later) requests; such knowledge can be in the form of specific user configuration or by remembering the version of a prior received response.
